[package]
name = "rust-spooler"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
actix-files = "0.6"
actix-multipart = "0.6"
futures = "0.3"
reqwest = { version = "0.11", features = ["json", "native-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "5.0"
tokio = { version = "1", features = ["full", "macros", "rt-multi-thread"] }
tempfile = "3.8"
local-ip-address = "0.6"
pusher-rs = {path = "pusher-rs"}